In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import root_mean_squared_error,r2_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import KFold

In [2]:
df=pd.read_csv('data/cleaned_data.csv')
df.head()

,Item_Weight,Item_Visibility,Item_MRP,Item_Outlet_Sales,Outlet_Age,Item_Fat_Content_Regular,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,...,Item_Type_Snack Foods,Item_Type_Soft Drinks,Item_Type_Starchy Foods,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,3735.1380,27,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,5.92,0.019278,48.2692,443.4228,17,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,17.50,0.016760,141.6180,2097.2700,27,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,19.20,0.070000,182.0950,732.3800,28,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,8.93,0.060000,53.8614,994.7052,39,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [4]:
x=df.drop('Item_Outlet_Sales',axis=1)
y=df['Item_Outlet_Sales']

In [5]:
x.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Age,Item_Fat_Content_Regular,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,...,Item_Type_Snack Foods,Item_Type_Soft Drinks,Item_Type_Starchy Foods,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,27,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,5.92,0.019278,48.2692,17,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,17.50,0.016760,141.6180,27,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,19.20,0.070000,182.0950,28,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,8.93,0.060000,53.8614,39,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [6]:
y

0       3735.1380
1        443.4228
2       2097.2700
3        732.3800
4        994.7052
          ...
8345    2778.3834
8346     549.2850
8347    1193.1136
8348    1845.5976
8349     765.6700
Name: Item_Outlet_Sales, Length: 8350, dtype: float64

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_train_scaled

array([[-1.18851289,  1.94819046,  0.24907441, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [ 1.29327522,  0.64811514, -0.88480987, ..., -1.41215191,
         2.82890357, -0.35750085],
       [ 0.50334741, -0.29103981, -1.34545126, ...,  0.70813911,
        -0.35349384, -0.35750085],
       ...,
       [-1.63653164,  0.70260641, -1.58111548, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [-1.47972508,  0.90272521, -0.89439901, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [-0.41627003, -1.31579445, -0.94415851, ...,  0.70813911,
        -0.35349384, -0.35750085]], shape=(6680, 27))

In [10]:
x_test_scaled=scaler.transform(x_test)
x_test_scaled

array([[-1.505663  , -0.77212347,  0.08821958, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [ 0.62124708,  0.85283594,  0.05514396, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [ 1.15179561, -0.87146815,  0.01721117, ...,  0.70813911,
        -0.35349384, -0.35750085],
       ...,
       [ 1.26969528, -0.29441272, -0.01919995, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [-1.74499934, -0.42803588, -0.19500831, ...,  0.70813911,
        -0.35349384, -0.35750085],
       [ 1.50549463, -0.75358739, -0.02025614, ...,  0.70813911,
        -0.35349384, -0.35750085]], shape=(1670, 27))

#### **Model Training**

##### 1. Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression
linear_model=LinearRegression()
linear_model.fit(x_train_scaled,y_train)

LinearRegression()

In [26]:
print("Training Score: ",linear_model.score(x_train_scaled,y_train))

Training Score:  0.5580630089888394

In [13]:
y_pred=linear_model.predict(x_test_scaled)

In [21]:
rmse=root_mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print(f"Root Mean Squared Error: {rmse}")
print(f"R2 Score: {r2}")

Root Mean Squared Error: 1116.5859495261866
R2 Score: 0.5542392507919478

#### 2. Lasso Regression

In [31]:
cv=KFold(n_splits=5)
param_grid={
    'alpha':[0.01,0.1,1,10,100],
    'max_iter':[1000,2000,3000,4000],
    'selection':['cyclic','random']
}

In [32]:
from sklearn.linear_model import Lasso
lasso_model=Lasso()
lasso_random=RandomizedSearchCV(estimator=lasso_model,param_distributions=param_grid,cv=cv,n_iter=10,scoring='r2',n_jobs=-1,verbose=2,random_state=42)
lasso_random.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=Lasso(), n_jobs=-1,
                   param_distributions={'alpha': [0.01, 0.1, 1, 10, 100],
                                        'max_iter': [1000, 2000, 3000, 4000],
                                        'selection': ['cyclic', 'random']},
                   random_state=42, scoring='r2', verbose=2)

In [33]:
print("Training Score: ",lasso_random.best_score_)

Training Score:  0.5545930613861847

In [34]:
lasso_random.best_params_

{'selection': 'random', 'max_iter': 2000, 'alpha': 10}

In [35]:
lasso_y_pred=lasso_random.predict(x_test_scaled)

In [36]:
print(f"Root Mean Squared Error: {root_mean_squared_error(y_test,lasso_y_pred)}")
print(f"R2 Score: {r2_score(y_test,lasso_y_pred)}")

Root Mean Squared Error: 1116.6590443445782
R2 Score: 0.5541808874075552

#### 3. Ridge Regression

In [37]:
param_grid1={
    'alpha':[0.01,0.1,1,10,100],
    'max_iter':[1000,2000,3000,4000],
    'solver':['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga', 'lbfgs']
}

In [38]:
from sklearn.linear_model import Ridge
ridge_model=Ridge()
ridge_random=RandomizedSearchCV(estimator=ridge_model,param_distributions=param_grid1,cv=cv,n_iter=10,scoring='r2',n_jobs=-1,verbose=2,random_state=42)
ridge_random.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

e:\Bigmart_Stores_Sales_Prediction\venv\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
5 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "e:\Bigmart_Stores_Sales_Prediction\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "e:\Bigmart_Stores_Sales_Prediction\venv\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "e:\Bigmart_Stores_Sales_Prediction\venv\lib\site-packages\sklearn\linear_model\_ridge.py", line 1248, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "e:\Bigmart_Stores_Sales_Prediction\venv\lib\site-packages\sklearn\linear_model\_ridge.py", line 914, in fit
    raise ValueError(
ValueError: 'lbfgs' solver can be used only when positive=True. Please use another solver.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
e:\Bigmart_Stores_Sales_Prediction\venv\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.55408484 0.55408499 0.55297726        nan 0.55407452 0.55406651
 0.55408716 0.55406768 0.55408499 0.55297571]
  warnings.warn(

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=Ridge(), n_jobs=-1,
                   param_distributions={'alpha': [0.01, 0.1, 1, 10, 100],
                                        'max_iter': [1000, 2000, 3000, 4000],
                                        'solver': ['auto', 'svd', 'cholesky',
                                                   'lsqr', 'sparse_cg', 'sag',
                                                   'saga', 'lbfgs']},
                   random_state=42, scoring='r2', verbose=2)

In [41]:
print("Training Score: ",ridge_random.best_score_)
ridge_y_pred=ridge_random.predict(x_test_scaled)
print(f"Root Mean Squared Error: {root_mean_squared_error(y_test,ridge_y_pred)}")
print(f"R2 Score: {r2_score(y_test,ridge_y_pred)}")

Training Score:  0.5540871613822216
Root Mean Squared Error: 1116.8147271353694
R2 Score: 0.5540565679883928

#### 4. Random Forest Regressor

In [42]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor()
param_grid2={
    'n_estimators':[100,200,300,400,500],
    'max_depth':[6,7,8,9,10],
    'min_samples_split':[8,9,10,11],
    'min_samples_leaf':[20,22,24,25]
}
rf_random=RandomizedSearchCV(estimator=rf_model,param_distributions=param_grid2,cv=cv,n_iter=100,n_jobs=-1,verbose=2,random_state=42,scoring='r2')
rf_random.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

KeyboardInterrupt: